### ISSUE TITLE
Нет игроков

### ISSUE THREAD

**Issue by GOSEF** [craft-soft/CS-Bans#12]
Игроки играют на сервере.
Но при переходе на конкретный сервер пишет
Детали сервера «СЕРВЕР»
Нет игроков

ниже справа, под картинкой:
Игроки:   18/30

Ubuntu 14.04 64bit

**Comment by urichalex** [comment]
Скрипт к этому не имеет отношения.
Если установлен Dproto выше 0.9.391, то откатить до этой версии, либо в dproto.cfg для параметра ServerInfoAnswerType установить значение 0

**Comment by GOSEF** [comment]
Ubuntu 14.04 64bit
6153
на голом метамоде 1,21,37 - нет игроков (правда, здесь ботов запускал - стимовцев не было)
метамод + dproto 0,9,391 + конфиг по-умолчанию (вставил только соль, ServerInfoAnswerType = 0) - нет игроков
дальнейшее добавление метамод плагинов даёт тот же результат...

**Comment by urichalex** [comment]
Проверьте без метамода и дпрото. Уверен игроки будут отображены. Поиграйте с параметром ServerInfoAnswerType, он принимает значения от 0 до 3 по-моему

**Comment by GOSEF** [comment]
Проблема проявляется при применении правила iptables:
iptables -A INPUT -p udp -m udp -m string --hex-string "|FFFFFFFF56|" --algo kmp -j DROP
пробовал так:
iptables -I INPUT -p udp -m udp -m string --hex-string "|FFFFFFFF56|" --algo kmp -j DROP

та же басня.

В iptables не понимаю - тупо убрал данное правило - игроки отображаются. Наверное, ослабил защиту сервера.

Если кто понимает, просьба помочь с фиксом этой ошибки.

Спасибо.

**Comment by hitmany** [comment]
LGSL нормально ваш сервер видит? Может изменить код мониторинга, а то таких ребята, опять найдутся и опять будут задавать подобный вопрос.

**Comment by GOSEF** [comment]
LGSL нормально ваш сервер видит?
- понятия не имею, т.к. никогда не связывался. В списке серверов отображается, при добавлении в мониторинг на сторонний сайтах проверку проходит (и отображался и проходил с вышеуказанным правилом iptables).
В моём случае проблема проявляется только как описано выше.

**Comment by urichalex** [comment]
Проверьте без метамода и дпрото. Уверен игроки будут отображены. Поиграйте с параметром ServerInfoAnswerType, он принимает значения от 0 до 3 по-моему

**Comment by GOSEF** [comment]
К чему это:
"Проверьте без метамода и дпрото. Уверен игроки будут отображены. Поиграйте с параметром ServerInfoAnswerType, он принимает значения от 0 до 3 по-моему"

Проблема обнаружена в правиле iptables:
iptables -A INPUT -p udp -m udp -m string --hex-string "|FFFFFFFF56|" --algo kmp -j DROP

Без данного правила всё отображается ровно. При его применении и с метамода и дпрото, и без оных игроков не видно...

**Comment by stamepicmorg** [comment]
рекомендую ставить ServerInfoAnswerType = 2
