### ISSUE TITLE
Не инсталлируется!

### ISSUE THREAD

**Issue by yoberlin** [Craft-Soft/CS-Bans#14]
Пишет что нет каталога и файла /site/install.html

Других ошибок нет. Ну могу проинсталлировать.
На том же сервере стоит Sourcebans, Amxbans так же инсталлируется в 3 клика.

В логах Апача: 

[Mon Jul 06 11:43:29 2015] [error] [client 92.78.25.84] File does not exist: /var/www/skillzonly/bans/site

Сам создал папку /site/ - и снова Апач:

[Mon Jul 06 11:44:02 2015] [error] [client 92.78.25.84] File does not exist: /var/www/skillzonly/bans/site/install.html

Что не так с архивом или поясните пожалуйста в деталях что я упустил?

**Comment by KirbyMagicman** [comment]
mod_rewrite включен?

**Comment by yoberlin** [comment]
Да, включён, специально проверял. У меня свой Дедик. Просто не ставится и всё, сейчас загружаю на другой хостинг, попробую там...

Может в архиве чего-то не хватает? Я например файлы поковырял и даже не нашёл там такой функции создающей каталог и файл.

Есть ли альтернативный способ установки? Например подставить уже готовый файл сгенерированный у Вас например?

**Comment by yoberlin** [comment]
На другом хостинге ничего не происходит, просто белая страница

**Comment by stamepicmorg** [comment]
@yoberlin https://github.com/Craft-Soft/CS-Bans/issues/3

с подключением.

**Comment by yoberlin** [comment]
.htaccess:

php_flag display_errors Off
php_flag session.cookie_httponly On
AddDefaultCharset UTF-8
Options -Indexes +FollowSymLinks

RewriteEngine on

# if a directory or a file exists, use it directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# otherwise forward it to index.php
RewriteRule . index.php

Вот что в ФТП... Так что именно мне прописать-то? У меня нет папки /bans/
Полный путь к каталогу: /var/www/skillzonly/bans/
![default](https://cloud.githubusercontent.com/assets/12736019/8523800/a5c97172-23f7-11e5-8ae2-53635de7020a.PNG)

**Comment by yoberlin** [comment]
http://ns378037.ip-5-196-89.eu/skillzonly/bans/site/install.html
Если это было для моего примера, то вот:

RewriteRule . /bans/index.php [L]

Добавил и по прежнему не работает....

**Comment by yoberlin** [comment]
/skillzonly/bans/index.php тоже пробовал
/www/skillzonly/bans/index.php тоже пробовал

**Comment by KirbyMagicman** [comment]
http://ns378037.ip-5-196-89.eu/skillzonly/bans/?r=site/install по такому пути всё работает, urlManager не трогали?

**Comment by yoberlin** [comment]
Нет, даже не знаю где он! Проинсталлировал, но даже страницу логина он только через это открывает и так со всеми страницами.... http://ns378037.ip-5-196-89.eu/skillzonly/bans/?r=site/login

Вы не поможете это поправить? У меня панель Webmin если что...

**Comment by urichalex** [comment]
Если по прямым ссылкам всё работает, значит не включен mod_rewrite или .htaccess игнорируется. Проверить в настройках хоста директиву AllowOverride
Да, и чем управляется веб сервер? Apache или Nginx?

**Comment by yoberlin** [comment]
Apache, сейчас директиву проверю... Это в настройках PHP? mod_rewrite 100% работает!

**Comment by yoberlin** [comment]
вот мой конфиг:  /etc/phpmyadmin/lighttpd.conf

# Alias for phpMyAdmin directory
alias.url += (
        "/phpmyadmin" => "/usr/share/phpmyadmin",
)

# Disallow access to libraries
$HTTP["url"] =~ "^/phpmyadmin/libraries" {
    url.access-deny = ( "" )
}
$HTTP["url"] =~ "^/phpmyadmin/setup/lib" {
    url.access-deny = ( "" )
}

# Limit access to setup script
$HTTP["url"] =~ "^/phpmyadmin/setup" {
        auth.backend = "htpasswd"
        auth.backend.htpasswd.userfile = "/etc/phpmyadmin/htpasswd.setup"
        auth.require = (
                "/" => (
                        "method" => "basic",
                        "realm" => "phpMyAdmin Setup",
                        "require" => "valid-user"
                )
        )
}

Надо что-то дописать? Для  AllowOverride?

**Comment by yoberlin** [comment]
И такое нашёл


Alias /phpmyadmin /usr/share/phpmyadmin

<Directory /usr/share/phpmyadmin>
        Options FollowSymLinks
        DirectoryIndex index.php

        <IfModule mod_php5.c>
                AddType application/x-httpd-php .php

                php_flag magic_quotes_gpc Off
                php_flag track_vars On
                php_flag register_globals Off
                php_admin_flag allow_url_fopen Off
                php_value include_path .
                php_admin_value upload_tmp_dir /var/lib/phpmyadmin/tmp
                php_admin_value open_basedir /usr/share/phpmyadmin/:/etc/phpmyadmin/:/var/lib/phpmyadmin/
        </IfModule>

</Directory>

# Authorize for setup
<Directory /usr/share/phpmyadmin/setup>
    <IfModule mod_authn_file.c>
    AuthType Basic
    AuthName "phpMyAdmin Setup"
    AuthUserFile /etc/phpmyadmin/htpasswd.setup
    </IfModule>
    Require valid-user
</Directory>

# Disallow web access to directories that don't need it
<Directory /usr/share/phpmyadmin/libraries>
    Order Deny,Allow
    Deny from All
</Directory>
<Directory /usr/share/phpmyadmin/setup/lib>
    Order Deny,Allow
    Deny from All
</Directory>

**Comment by urichalex** [comment]
При чем тут PhpMyAdmin????????????
Настройки Вашего хоста в Apache

**Comment by yoberlin** [comment]
А в каком файле искать то? Там масса конфигов...

**Comment by yoberlin** [comment]
/etc/phpmyadmin/lighttpd.conf
/usr/share/doc/libapache2-mod-ruby/examples/httpd.conf-apache2

**Comment by yoberlin** [comment]
Настройки ведь хранятся в httpd.conf?
locate httpd.conf выдала 2 строчки выше постом...

**Comment by iamkapman** [comment]
Конфиги Apache лежат в /etc/apache2

**Comment by yoberlin** [comment]
Спасибо! Там нет... Через гугл выгуглил )

apache2.conf allow override
